name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup yq
        uses: mikefarah/yq@v4
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Validate schemas
        run: |
          set -euxo pipefail

          # mirror kustomize-controller build options
          kustomize_flags=("--load-restrictor=LoadRestrictionsNone")
          kustomize_config="kustomization.yaml"

          # skip Kubernetes Secrets due to SOPS fields failing validation
          kubeconform_flags=("-skip=Secret")
          kubeconform_config=("-strict" "-ignore-missing-schemas" "-schema-location" "default" "-schema-location" "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json" "-verbose")

          echo "INFO - Validating kustomize overlays"
          find . -type f -name $kustomize_config -print0 | while IFS= read -r -d $'\0' file;
            do
              echo "INFO - Validating kustomization ${file/%$kustomize_config}"
              kustomize build "${file/%$kustomize_config}" "${kustomize_flags[@]}" | \
                kubeconform "${kubeconform_flags[@]}" "${kubeconform_config[@]}"
              if [[ ${PIPESTATUS[0]} != 0 ]]; then
                exit 1
              fi
          done
